### What is Numpy ?

> Numpy is a python library is the fundamental library for the numerical computation. It is an integral part of the Scientific Python Ecosystem.

> We make use of numpy library to store raw data. It has a basic
yet very versatile data structure known as Ndarray which refers to **N-dimensional array**

> Designed to handle large scientific, mathematical, and multidimensional datasets (vectors, matrices, tensors).

#### But why do we need to use Numpy when we can have list or dict or even set data strucutre to perfrom the mentioned tasks ?

> The reason behind using Numpy library is due to its performance speed when handling large data set as it performs calculations at native C-speed using vectorization (operating on whole arrays without slow Python for loops), serving as the backbone for Pandas, Scikit-learn, and PyTorch.

> Additionally, unlike Python lists, all items in an ndarray must share the exact same data type.

> To use numpy library in python we must first import it as shown:  
 `import numpy as np` where np is an alias for numpy that is commonly used among developers  

In [148]:
import numpy as np

> NumPy arrays can be defined using Python sequences such as lists and tuples. Both list and tuples define the ndarray creation:
>
>1 - a list of numbers forms a 1D array
>
>2 - a list of lists form a 2D array
>
> 3- Nested lists or tuples will form a higher array dimension as in N-dimensional array  
>
> Since any numerical data in the form of lists or tuples they must be converted to array inorder to have them be used in NumPy.
>
> **As NumPy base data type is array object.**

>
#### How can we define a new array using NumPy ?
> To define a new array using NumPy we must first **import numpy** library to get access to all of its methods
>
> numpy.array() is used to convert lists into array
>
> Then we make use of the library name or its alias (commonly used is **np** so it becomes **import nmupy as np**) and the since we are dealing with built in method we make us of dot notation concept to invoke the **array(paramter: list or tuple)** method


```
numpy.array(argument)
```
>
> The following syntax will illustrate the type casting of lists and tuples to make them useful and usable for NumPy library

In [149]:
# creating a list to illustrate type conversion
lst1 = [1,2]
lst2 = [3,5]
print(f"first list is of type: {type(lst1)}\nholding the data: {lst1}\nsecond list is of type {type(lst2)}\nholding the data: {lst2}\n")

######## creating a 1D array using lst1
d1 = np.array(lst1)
print(f"feeding the list one to array of d1: {d1}\nis of type: {type(d1)} and it is a 1D array\n")

######## creating a 1D array using lst2
d1_2 = np.array(lst2)
print(f"feeding the list two to array of d1: {d1}\nis of type: {type(d1)} and it is a 1D array\n")

######## creating a 2D array using both lst1 and lst2
d2 = np.array([lst1,lst2])
print(f"feeding the list one and two to array of d2:\n{d2}\nis of type: {type(d2)} and it is a 2D array\n")

first list is of type: <class 'list'>
holding the data: [1, 2]
second list is of type <class 'list'>
holding the data: [3, 5]

feeding the list one to array of d1: [1 2]
is of type: <class 'numpy.ndarray'> and it is a 1D array

feeding the list two to array of d1: [1 2]
is of type: <class 'numpy.ndarray'> and it is a 1D array

feeding the list one and two to array of d2:
[[1 2]
 [3 5]]
is of type: <class 'numpy.ndarray'> and it is a 2D array



----

#### NumPy Concepts 
 
> - ndarrary object: N-dimensional array for fast numerical operations 
>
> - Vectorized operations: perform element-wise calculation without loops (vector calculations)
>
> - Broadcasting: operate on arrays of different shapes 
>
> - Linear algebar functions: Matrix operations like multiplication and inversion 
>
> - Statistical functions: mean, median, standard deviation
>
> - Integration: works with Pandas, SciPy and scikit-learn

## Using Numpy Functions
--- 
#### 1D 
> - **numpy.zeros((rowNum, colNum))**
> ---
> - **numpy.ones((rowNum, colNum))**
> ---
> - **numpy.arange(statNum,stopNum,jumps)** or **numpy.arange(num)**
> --- 
> - **numpy.linespace(startNum, stopNum, jumps)** 
>> Creates array with specified number of elements and spaced equally between specified begining to end 
value. The calcualtion that happens behind this function is an Arithmetic Sequence formula: **(endNum-startNum)/(steps-1)** 
---


## numpy.zeros()
>>### **Syntax**
>> - **numpy.zeros((rowNum, colNum))**

In [150]:
a2 = np.zeros((3,3))
print(f"This is array with all zeros in it: \n{a2}\n")

This is array with all zeros in it: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



## numpy.ones()
>> ### **Syntax**
>> - **numpy.ones((rowNum, colNum))**

In [151]:
a1 = np.ones((3,3))
print(f"This is array with all ones in it: \n{a1}")

This is array with all ones in it: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## numpy.arange()
>> ### **Syntax**
>> - **numpy.arange(statNum,stopNum,jumps)** 
>>
>> or
>>
>> - **numpy.arange(num)**
>>
>> or
>>
>> - **numpy.arange(statNum,stopNum)** 
>>

In [152]:
## usign start,end and number of jumps 
a3 = np.arange(0,10,2)
print(f"This is array with values from 0 to 10 skipping 2 : \n{a3}\n")

## using single number
a4 = np.arange(16)
print(f"This is array with values from 0 to 15 inclusive : \n{a4}\n")

## using start and end only 
a5 = np .arange(-1,21)
print(f"This is array with values from -1 to 20 inclusive : \n{a5}\n")



This is array with values from 0 to 10 skipping 2 : 
[0 2 4 6 8]

This is array with values from 0 to 15 inclusive : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

This is array with values from -1 to 20 inclusive : 
[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]



## numpy.linespace()
>> ### **Syntax**
>> - **numpy.linspace(startNum, stopNum, jumps)** 
>>
>> Creates array with specified number of elements and spaced equally between specified begining to end 
value. The calcualtion that happens behind this function is an Arithmetic Sequence formula:
>> 
>> **(endNum-startNum)/(steps-1)** 


In [153]:
startNum = 1
endNum = 4
steps = 3
a6 = np.linspace(startNum,endNum,steps)
print(f"{a6}")
print(f"Using the arithmetic formula to calculate the interval spaces: {(endNum-startNum)/(steps-1)}")
## testing case 
test = (endNum-startNum)/(steps-1)
assert startNum + test == 2.5, "test case failed"

[1.  2.5 4. ]
Using the arithmetic formula to calculate the interval spaces: 1.5


In [154]:
a1 = np.ones((3,3))
print(f"This is array with all ones in it: {a1}\n")
a2 = np.zeros((3,3))
print(f"This is array with all zeros in it: {a2}\n")
a3 = np.arange(0,10,2)
print(f"This is array with values from 0 to 10 skipping 2 : {a3}\n")
a4 = np.linspace(1.,12.,3)
print(f"Array with linspace: {a4}\n")



This is array with all ones in it: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

This is array with all zeros in it: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

This is array with values from 0 to 10 skipping 2 : [0 2 4 6 8]

Array with linspace: [ 1.   6.5 12. ]



--- 
### NumPy Array Indexing
> NumPy array supports indexing to access the array elements using thier positions 
### Advanced indexing 
> NumPy provides more flexible ways to access and manipulate array elements through mulitple indexing **np.array([index1,index2,..])** or simply **indx = [index1,index2,..]**
>
> We also have **Boolean indexing**:  **var1 = array condition**

In [155]:
arr1 = np.array([1,2,3,4,5,6])
print(f"Print the first item: {arr1[0]}")
print(f"Print the last item: {arr1[-1]}")
print(f"Print the second last item: {arr1[-2]}")

## using 2D array 
arr2 = np.array([[1,2,3],[1,2,3]])
print(f"Print the third item in the given: \n{arr2}\n is: {arr2[0,2]}\n")

## Advanced indexing 
## using arr1 
indx = [0,2,4]
indx2 = arr1 > 2 ## boolean indexing 
print(f"Using index 0,2,4: {arr1[indx]}")
print(f"Using advanced index having items more than 2: {arr1[indx2]}")

Print the first item: 1
Print the last item: 6
Print the second last item: 5
Print the third item in the given: 
[[1 2 3]
 [1 2 3]]
 is: 3

Using index 0,2,4: [1 3 5]
Using advanced index having items more than 2: [3 4 5 6]


----
### Basic Arithmetic Operation 
> Without using a for loop or while loop we can perform direct addition, multiplication, subtraction and division to the array matrices and retrieve an output 

In [156]:
arr1 = np.array([3,3,4])
arr2 = np.array([1,2,3])
print(f"Addition of arr1 and arr2: {arr1+arr2}")
print(f"Subtraction of arr1 and arr2: {arr1-arr2}")
print(f"Division of arr1 and arr2: {arr1/arr2}")
print(f"Multiplication of arr1 and arr2: {arr1*arr2}")

Addition of arr1 and arr2: [4 5 7]
Subtraction of arr1 and arr2: [2 1 1]
Division of arr1 and arr2: [3.         1.5        1.33333333]
Multiplication of arr1 and arr2: [ 3  6 12]


---
### Unary Operation 
> Applies a single operand transformation such as negation (NOT), absolute value (converting negative sign to positive) or trigonometic evaluation
> 
> **numpy.absolute(array)** 

In [157]:
arr4 = np.array([-3,-1,0,1,2])
print(np.absolute(arr4))

[3 1 0 1 2]


---
### arrVar.size

> Retrieve size of the array of any dimension 

In [158]:
arr1 = np.array([[1,2,3],[1,2,4]])
print(arr1.size)

6


--- 
### Different way to create array 
> - np.full(shape, fillValue)  : Creates an array filled with a specified value 
>> **shape defines the row X column number**
>> **fillValue scalar or array like value/s
>> The method returns a new array of given shape and type, filled with fill_value
>
> NumPy provides functions to create arrays filled with random numbers.
>
> - np.random.rand(): Creates an array of specified shape and fills it with random values sampled from a uniform distribution over [0, 1).
> - np.random.randn(): Creates an array of specified shape and fills it with random values sampled from a standard normal distribution.
> - np.random.randint(): Creates an array of specified shape and fills it with random integers within a given range.

In [159]:
arr1 = np.full(shape = (4,3),fill_value = [1,2,4])
arr2 = np.full(shape = (2,2),fill_value= 7)
print(f"{arr1}\n")
print(arr2)

[[1 2 4]
 [1 2 4]
 [1 2 4]
 [1 2 4]]

[[7 7]
 [7 7]]


In [160]:
arr1 =np.random.rand(2,3,7,1) # 2 block each has 3 rows and each block has 7 row and 1 column 
arr2 = np.random.randn(2,3)
arr3 = np.random.randint(low = 0, high= 2, size=(4,4))
print(f"{arr1}\n")
print(f"{arr2}\n")
print(f"{arr3}\n")

[[[[0.20644106]
   [0.62918101]
   [0.46452026]
   [0.7525466 ]
   [0.42861961]
   [0.35513237]
   [0.0933857 ]]

  [[0.27889482]
   [0.4317651 ]
   [0.34291658]
   [0.89723885]
   [0.0583543 ]
   [0.63681348]
   [0.4884058 ]]

  [[0.86431684]
   [0.96882735]
   [0.21350795]
   [0.48454798]
   [0.06856678]
   [0.94568668]
   [0.84727092]]]


 [[[0.0022377 ]
   [0.95614749]
   [0.55379847]
   [0.22763541]
   [0.58521778]
   [0.98352502]
   [0.88870196]]

  [[0.06818496]
   [0.29487943]
   [0.98408613]
   [0.93441482]
   [0.29237239]
   [0.21931491]
   [0.43686386]]

  [[0.21844641]
   [0.6738979 ]
   [0.81628945]
   [0.03004495]
   [0.96672023]
   [0.04336152]
   [0.4657131 ]]]]

[[-0.99970565 -1.2079541  -0.89888239]
 [ 0.36175147 -2.04592057 -0.61316301]]

[[0 1 0 1]
 [0 1 1 0]
 [0 0 0 0]
 [0 0 1 0]]



---
### arrVar.dtype
> A method that returns the data type of the array provided

In [161]:
arr1 = np.array([1,2,3])
print(f"Array data type is: {arr1.dtype}")

Array data type is: int64


---
### Idenity Matrix
> In NumPy to create an identity matrix of square n x n we have a method called: 
>
>**numpy.eye(N,M,k)**
>> **N is the number of rows** 
>>
>> **M is the number of columns** 
>>
>> **k is the shift of the main diagonal 1's by n number to the right side k > 0 shifts upper/right, k < 0 shifts lower/left** 

In [ ]:
identityArrN = np.eye(3 ,dtype=int) #n x n => 3x3 
identityArrNM = np.eye(3,2 ,dtype=int) # n x m => 3 x 2
identityArrNMKR = np.eye(3,3,k=1,dtype=int) # n x n => 3 x 3 , k => 1 
identityArrNMKL = np.eye(3,3,k=-1,dtype=int) # n x m => 3 x 3  , k => -1 

print(f"This is a 3 by 3 matrix: \n{identityArrN}\n")
print(f"This is a 3 by 2 matrix: \n{identityArrNM}")
print(f"This is a 3 by 3 matrix, shifting it by 1 to righ, up: \n{identityArrNMKR}")
print(f"This is a 3 by 3 matrix, shifting it by 1 to left, down : \n{identityArrNMKL}")


This is a 3 by 3 matrix: 
[[1 0 0]
 [0 1 0]
 [0 0 1]]

This is a 3 by 2 matrix: 
[[1 0]
 [0 1]
 [0 0]]
This is a 3 by 3 matrix, shifting it by 1 to right: 
[[0 1 0]
 [0 0 1]
 [0 0 0]]
This is a 3 by 3 matrix, shifting it by 1 to left: 
[[0 0 0]
 [1 0 0]
 [0 1 0]]
